{"level":"INFO","message":"[6:30:06.020 PM]: Creating new connection object"}
{"level":"INFO","message":"[6:30:08.478 PM]: Creating Connection[id: 4406b425-7388-4c0e-808f-0642039eba5c] with host: tdztiko-pvb41526.snowflakecomputing.com, account: tdztiko-pvb41526, accessUrl: https://tdztiko-pvb41526.snowflakecomputing.com, user: SHIVANIP, role: undefined, database: DASH_DB, schema: DASH_SCHEMA, warehouse: DASH_S, proxy was not configured, password is not provided, region: undefined, authenticator: SNOWFLAKE_JWT, ocsp mode: FAIL_OPEN, os: win32, os version: 10.0.22000"}
{"level":"INFO","message":"[6:30:08.481 PM]: Connection[id: 4406b425-7388-4c0e-808f-0642039eba5c] additional details: passcode in password is provided, passcode is not provided, private key is not provided, application: undefined, client name: snowflake-sdk, client version: 2.1.3, retry timeout: 300, private key path: rsa_key.p8, private key pass is not provided, client store temporary credential: false, browser response timeout: 120000"}
{"level":"INFO","message":"[6:30:08.487 PM]: Connection[id: 4406b425-7388-4c0e-808f-0642039eba5c] - connection object created successfully."}
{"level":"INFO","message":"[6:30:08.490 PM]: Connection[id: 4406b425-7388-4c0e-808f-0642039eba5c] - connecting. Associated Snowflake domain: GLOBAL"}
{"level":"ERROR","message":"[6:30:08.497 PM]: Connection[id: 4406b425-7388-4c0e-808f-0642039eba5c] - authentication failed. Error: Error: error:07880109:common libcrypto routines::interrupted or cancelled\n    at Object.createPrivateKey (node:internal/crypto/keys:632:12)\n    at loadPrivateKey (E:\\CortexTeamsBot\\CortexBot\\node_modules\\snowflake-sdk\\dist\\lib\\authentication\\auth_keypair.js:58:39)\n    at AuthKeypair.authenticate (E:\\CortexTeamsBot\\CortexBot\\node_modules\\snowflake-sdk\\dist\\lib\\authentication\\auth_keypair.js:110:26)\n    at Connect"}
{"level":"INFO","message":"[6:34:36.780 PM]: Creating new connection object"}
{"level":"INFO","message":"[6:34:36.812 PM]: Creating Connection[id: cef70465-820c-431b-afb8-02f7ff04af71] with host: tdztiko-pvb41526.snowflakecomputing.com, account: tdztiko-pvb41526, accessUrl: https://tdztiko-pvb41526.snowflakecomputing.com, user: SHIVANIP, role: ACCOUNTADMIN, database: DASH_DB, schema: DASH_SCHEMA, warehouse: DASH_S, proxy was not configured, password is provided, region: undefined, authenticator: SNOWFLAKE, ocsp mode: FAIL_OPEN, os: win32, os version: 10.0.22000"}
{"level":"INFO","message":"[6:34:36.815 PM]: Connection[id: cef70465-820c-431b-afb8-02f7ff04af71] additional details: passcode in password is provided, passcode is not provided, private key is not provided, application: undefined, client name: snowflake-sdk, client version: 2.1.3, retry timeout: 300, private key path: undefined, private key pass is not provided, client store temporary credential: false, browser response timeout: 120000"}
{"level":"INFO","message":"[6:34:36.819 PM]: Connection[id: cef70465-820c-431b-afb8-02f7ff04af71] - connection object created successfully."}
{"level":"INFO","message":"[6:34:36.822 PM]: Connection[id: cef70465-820c-431b-afb8-02f7ff04af71] - connecting. Associated Snowflake domain: GLOBAL"}
{"level":"INFO","message":"[6:34:36.824 PM]: Connection[id: cef70465-820c-431b-afb8-02f7ff04af71] - authentication successful using: SNOWFLAKE"}
{"level":"INFO","message":"[6:34:36.826 PM]: Trying to initialize Easy Logging"}
{"level":"INFO","message":"[6:34:36.836 PM]: No client config detected."}
{"level":"INFO","message":"[6:34:36.838 PM]: No config file path found. Client config will not be used."}
{"level":"INFO","message":"[6:34:36.840 PM]: Easy Logging is disabled as no config has been found"}
{"level":"INFO","message":"[6:34:36.852 PM]: Connection[id: cef70465-820c-431b-afb8-02f7ff04af71] - connected successfully after 30.301700115203857 milliseconds"}
{"level":"INFO","message":"[6:35:32.842 PM]: Creating new connection object"}
{"level":"INFO","message":"[6:35:32.871 PM]: Creating Connection[id: 65159460-67f0-41b0-9823-d0b5ffbdda4c] with host: tdztiko-pvb41526.snowflakecomputing.com, account: tdztiko-pvb41526, accessUrl: https://tdztiko-pvb41526.snowflakecomputing.com, user: SHIVANIP, role: ACCOUNTADMIN, database: DASH_DB, schema: DASH_SCHEMA, warehouse: DASH_S, proxy was not configured, password is provided, region: undefined, authenticator: SNOWFLAKE, ocsp mode: FAIL_OPEN, os: win32, os version: 10.0.22000"}
{"level":"INFO","message":"[6:35:32.873 PM]: Connection[id: 65159460-67f0-41b0-9823-d0b5ffbdda4c] additional details: passcode in password is provided, passcode is not provided, private key is not provided, application: undefined, client name: snowflake-sdk, client version: 2.1.3, retry timeout: 300, private key path: undefined, private key pass is not provided, client store temporary credential: false, browser response timeout: 120000"}
{"level":"INFO","message":"[6:35:32.876 PM]: Connection[id: 65159460-67f0-41b0-9823-d0b5ffbdda4c] - connection object created successfully."}
{"level":"INFO","message":"[6:35:32.878 PM]: Connection[id: 65159460-67f0-41b0-9823-d0b5ffbdda4c] - connecting. Associated Snowflake domain: GLOBAL"}
{"level":"INFO","message":"[6:35:32.879 PM]: Connection[id: 65159460-67f0-41b0-9823-d0b5ffbdda4c] - authentication successful using: SNOWFLAKE"}
{"level":"INFO","message":"[6:35:32.881 PM]: Trying to initialize Easy Logging"}
{"level":"INFO","message":"[6:35:32.887 PM]: No client config detected."}
{"level":"INFO","message":"[6:35:32.889 PM]: No config file path found. Client config will not be used."}
{"level":"INFO","message":"[6:35:32.890 PM]: Easy Logging is disabled as no config has been found"}
{"level":"INFO","message":"[6:35:32.897 PM]: Connection[id: 65159460-67f0-41b0-9823-d0b5ffbdda4c] - connected successfully after 19.753100156784058 milliseconds"}
